AS=as --32
CC=gcc -m32 -march=i686 -nostdlib
LD=ld -m elf_i386
OBJCOPY=objcopy
QEMU=qemu-system-i386
BOCHS=bochs
STRIP=strip
_ALLWARN=-Wall -Wextra -Waddress -Wconversion
CFLAGS=-g -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce $(_ALLWARN)