# 实验 1 初识实验环境

BIN = hello
all: BIN

hello
	gcc -O4 hello.c -o hello

# There are several bugs in the Makefile
# Please fix this and
# change the output target name to the passcode+(first commit hash 5 digits)
# e.g: passcode is shanamoe
# commit: 4c10a3dc5ef5168eead13691b4a0eeb33552d9a0
# Then the target is shanamoe4c10a